export const defaultTemplates = {
    birthday_wa: "[LAMS NOTIFICATION]\n\nDear {name},\n\nWishing you a very Happy Birthday from the College Administration. We hope you have a wonderful day and a successful year ahead!\n\n--\nCollege Administration",
    anniversary_wa: "[LAMS NOTIFICATION]\n\nDear {name},\n\nCongratulations on completing {years} of dedicated service with our institution. We appreciate your continued commitment.\n\n--\nCollege Administration",
    holiday_push_title: "Holiday Notification",
    holiday_push_body: "Today is {holiday_name}. Regular classes are suspended.",
    holiday_wa: "[LAMS NOTIFICATION]\n\nDear Faculty & Staff,\n\nPlease be informed that today is {holiday_name}. Regular classes and academic activities are suspended for the day.\n\n--\nCollege Administration",
    warn1_push_title: "Upcoming Class",
    warn1_push_body: "Reminder: {subject} ({group}){cofacInline} begins in {mins} mins at Room {room}.",
    warn1_wa: "[LAMS REMINDER]\n\nDear Faculty,\n\nYou have an upcoming class scheduled to begin in {mins} minutes.\n\nDETAILS:\nSubject: {subject} ({group})\nStarts In: {mins} mins\nRoom: {room}{cofacStr}\n\nPlease proceed to your designated classroom.\n\n--\nLAMS System",
    warn2_push_title: "Class Starting",
    warn2_push_body: "Action Required: {subject} ({group}){cofacInline} is starting now at Room {room}.",
    warn2_wa: "[LAMS ALERT]\n\nDear Faculty,\n\nYour scheduled class is starting now. Please proceed to your classroom immediately.\n\nDETAILS:\nSubject: {subject} ({group})\nStatus: Starting Now\nRoom: {room}{cofacStr}\n\n--\nLAMS System",
    weekly_header: "[LAMS WEEKLY SCHEDULE]\n\nDear {name},\n\nHere is your official schedule for the upcoming week. Total assigned sessions: {total_sessions}.\n\n",
    weekly_class_line: "{idx}. {time} : {group} [{subject}]{cofacStr}{roomStr}{semStr}{subStr}\n",
    weekly_footer: "\nPlease verify this schedule on the LAMS portal.\n\n--\nCollege Administration",
    morning_header: "[LAMS DAILY SCHEDULE]\n\nDear {name},\n\nHere is your official itinerary for today ({day}). Total assigned classes: {total_classes}.\n\n",
    morning_class_line: "{idx}. {time} : {group} [{subject}]{cofacStr}{roomStr}{semStr}{subStr}\n",
    morning_footer: "\n--\nCollege Administration",
    sys_sub_req: "[LAMS NOTIFICATION: SUBSTITUTION REQUEST]\n\nDear {name},\n\nYou have received a substitution request from {requesterName}.\n\nDETAILS:\nSubject: {subject} ({group})\nRoom: {room}\nSchedule: {day}, {date} at {time}{cofacStr}\n\nPlease log in to the LAMS portal to formally accept or decline this request.\n\n--\nLAMS System",
    sys_sub_app: "[LAMS NOTIFICATION: SUBSTITUTION APPROVED]\n\nDear {name},\n\nYour substitution arrangement has been formally processed and approved by the Administration.\n\nDETAILS:\nSubject: {subject}{cofacInline}\nSchedule: {day}, {date}\nCovered By: {subName}\n\n--\nCollege Administration",
    sys_sub_rej: "[LAMS NOTIFICATION: SUBSTITUTION DECLINED]\n\nDear {name},\n\nYour substitution arrangement has been declined or cancelled.\n\nDETAILS:\nSubject: {subject}{cofacInline}\nSchedule: {day}, {date}\nStatus: Declined / Cancelled\n\nPlease log in to the portal to review your schedule.\n\n--\nCollege Administration",
    sys_sub_acc: "[LAMS NOTIFICATION: SUBSTITUTION ACCEPTED]\n\nDear {name},\n\nYour substitution request has been accepted by {subName}.\n\nDETAILS:\nSubject: {subject}{cofacInline}\nSchedule: {day}, {date}\nAccepted By: {subName}\n\nStatus: Pending final Administrative approval.\n\n--\nLAMS System",
    sys_sub_can: "[LAMS NOTIFICATION: SUBSTITUTION CANCELLED]\n\nDear {name},\n\nA previously requested substitution has been cancelled.\n\nDETAILS:\nSubject: {subject}{cofacInline}\nSchedule: {day}, {date}\n\nYou are now expected to conduct this class yourself.\n\n--\nCollege Administration",
    sys_sub_can_sub: "[LAMS NOTIFICATION: COVERAGE CANCELLED]\n\nDear {name},\n\nA substitution arrangement you were assigned to cover has been cancelled.\n\nDETAILS:\nSubject: {subject}{cofacInline}\nSchedule: {day}, {date}\n\nYou are no longer required to cover this class.\n\n--\nCollege Administration",
    sys_req_can: "[LAMS NOTIFICATION: REQUEST WITHDRAWN]\n\nDear {name},\n\nA peer has withdrawn their request for you to cover their class.\n\nDETAILS:\nSubject: {subject}{cofacInline}\nSchedule: {day}, {date}\nStatus: Request Withdrawn\n\n--\nCollege Administration",
    sys_new_assign: "[LAMS NOTIFICATION: NEW ASSIGNMENT]\n\nDear {name},\n\nA new academic assignment has been added to your profile.\n\nDETAILS:\n{body}\n\n--\nCollege Administration",
    sys_alert: "[LAMS ADMIN ANNOUNCEMENT]\n\n{title}\n\n{body}\n\n--\nSystem Broadcast",
    sys_acc_app: "[LAMS NOTIFICATION: ACCOUNT APPROVED]\n\nDear {name},\n\nYour faculty account has been successfully verified and approved by the Administration.\n\nYou may now log in to the LAMS portal to access your schedule.\nPortal: https://lams.vercel.app\n\n--\nCollege Administration",
    obs_sub_app: "[LAMS ADMIN ALERT: LEAVE COVERED]\n\nA substitution arrangement has been finalized.\n\nDETAILS:\nOn Leave: {requesterName}\nSubstitute: {subName}\nClass: {subject} ({group}){cofacInline}\nSchedule: {day}, {date} at {time}\nRoom: {room}",
    obs_sub_can: "[LAMS ADMIN ALERT: SUB CANCELLED]\n\nA substitution arrangement has been revoked.\n\nDETAILS:\nClass: {subject} ({group}){cofacInline}\nSchedule: {day}, {date} at {time}\nRoom: {room}",
    obs_bday: "[LAMS ADMIN ALERT: BIRTHDAY]\n\nToday is {name}'s birthday!",
    obs_anni: "[LAMS ADMIN ALERT: WORK ANNIVERSARY]\n\n{name} is celebrating {years} years with us today!"
};
