export const defaultTemplates = {
    birthday_wa: "🎉 *HAPPY BIRTHDAY!* 🎉\n\nDear *{name}*,\nWishing you a fantastic day filled with joy, and a year ahead full of success and happiness! Keep inspiring our students and staff! 🎂✨\n\n━━━━━━━━━━━━━━\n~ *College Administration*",
    anniversary_wa: "🎊 *WORK ANNIVERSARY* 🎊\n\nDear *{name}*,\nCongratulations on completing *{years}* with our institution! 🏫\n\nThank you for your incredible dedication, hard work, and commitment to excellence. We are proud to have you on our team! 🌟\n\n━━━━━━━━━━━━━━\n~ *College Administration*",
    holiday_push_title: "🎉 Holiday Alert",
    holiday_push_body: "Today is {holiday_name}. No classes today. Enjoy!",
    holiday_wa: "🏝️ *HOLIDAY ANNOUNCEMENT* 🏝️\n\nDear Faculty & Staff,\nWishing everyone a wonderful *{holiday_name}*! 🎉\nPlease enjoy your time off and return refreshed.\n\n━━━━━━━━━━━━━━\n~ *College Administration*",
    warn1_push_title: "Upcoming Class",
    warn1_push_body: "🔔 Heads Up: {subject} ({group}){cofacInline} starts in {mins} mins at Room {room}.",
    warn1_wa: "🔔 *UPCOMING CLASS ALERT* 🔔\n\nHello,\nYou have a class scheduled to begin shortly.\n\n━━━━━━━━━━━━━━\n📋 *CLASS DETAILS*\n🔹 *Subject:* {subject} ({group})\n🔹 *Starts In:* {mins} mins\n🔹 *Room:* {room}{cofacStr}\n━━━━━━━━━━━━━━\n\n👉 _Please proceed to your classroom._",
    warn2_push_title: "Class Starting!",
    warn2_push_body: "🚀 ACTION: Run to Room {room}! {subject} ({group}){cofacInline} is starting NOW!",
    warn2_wa: "🚀 *CLASS STARTING NOW* 🚀\n\n🚨 _ACTION REQUIRED: Proceed to Room {room} immediately._\n\n━━━━━━━━━━━━━━\n📋 *CLASS DETAILS*\n🔹 *Subject:* {subject} ({group})\n🔹 *Status:* Starting NOW!{cofacStr}\n━━━━━━━━━━━━━━",
    weekly_header: "🗓️ *WEEKLY SCHEDULE PREVIEW* 🗓️\n\nHello *{name}*,\nHere is your official schedule for the upcoming week. You have a total of *{total_sessions} sessions*.\n\n━━━━━━━━━━━━━━\n",
    weekly_class_line: "🔹 *[{idx}]* {time} | *{subject}* ({group}){roomStr}{semStr}{cofacStr}{subStr}\n",
    weekly_footer: "━━━━━━━━━━━━━━\n🌐 _Please check the LAMS portal for real-time updates._\nHave a highly productive week! 💪",
    morning_header: "🌅 *GOOD MORNING, {name}!* 🌅\n\nHere is your official itinerary for today (*{day}*). You are scheduled for *{total_classes} classes*.\n\n━━━━━━━━━━━━━━\n",
    morning_class_line: "🔹 *[{idx}]* {time} | *{subject}* ({group}){roomStr}{semStr}{cofacStr}{subStr}\n",
    morning_footer: "━━━━━━━━━━━━━━\n💡 _Wishing you a successful and productive day ahead._\n~ *College Administration*",
    sys_sub_req: "🔄 *NEW SUBSTITUTION REQUEST* 🔄\n\nHello *{name}*,\nYou have received a substitution request from *{requesterName}*.\n\n━━━━━━━━━━━━━━\n📋 *REQUEST DETAILS*\n🔹 *Subject:* {subject} ({group})\n🔹 *Room:* {room}\n🔹 *When:* {day}, {date} at {time}{cofacStr}\n━━━━━━━━━━━━━━\n\n👉 _Please log in to the portal to Accept or Reject._",
    sys_sub_app: "✅ *SUBSTITUTION APPROVED* ✅\n\nHello *{name}*,\nYour substitution arrangement has been officially processed and approved.\n\n━━━━━━━━━━━━━━\n📋 *APPROVAL SUMMARY*\n🔹 *Subject:* {subject}{cofacInline}\n🔹 *When:* {day}, {date}\n🔹 *Covered By:* {subName}\n━━━━━━━━━━━━━━\n\n~ *College Administration*",
    sys_sub_rej: "❌ *SUBSTITUTION DECLINED* ❌\n\nHello *{name}*,\nUnfortunately, your substitution arrangement could not be processed.\n\n━━━━━━━━━━━━━━\n📋 *DECLINED SUMMARY*\n🔹 *Subject:* {subject}{cofacInline}\n🔹 *When:* {day}, {date}\n🔹 *Status:* Declined / Cancelled\n━━━━━━━━━━━━━━\n\nℹ️ *Info:* Please log in to the portal to review your schedule.",
    sys_sub_acc: "🎉 *SUBSTITUTION ACCEPTED* 🎉\n\nHello *{name}*,\nYour substitution request has been accepted by *{subName}*!\n\n━━━━━━━━━━━━━━\n📋 *CONFIRMATION DETAILS*\n🔹 *Subject:* {subject}{cofacInline}\n🔹 *When:* {day}, {date}\n🔹 *Accepted By:* {subName}\n━━━━━━━━━━━━━━\n\n⏳ _Waiting for final Admin approval._",
    sys_sub_can: "⚠️ *SUBSTITUTION CANCELLED* ⚠️\n\nHello *{name}*,\nA previously requested substitution duty has been cancelled.\n\n━━━━━━━━━━━━━━\n📋 *CANCELLATION DETAILS*\n🔹 *Subject:* {subject}{cofacInline}\n🔹 *When:* {day}, {date}\n━━━━━━━━━━━━━━\n\nℹ️ *Info:* You are now expected to conduct this class yourself.",
    sys_new_assign: "📚 *NEW CLASS ASSIGNMENT* 📚\n\nHello *{name}*,\nA new academic assignment has been added to your profile.\n\n━━━━━━━━━━━━━━\n📋 *ASSIGNMENT DETAILS*\n{body}\n━━━━━━━━━━━━━━\n\n~ *College Administration*",
    sys_alert: "📢 *ADMIN ANNOUNCEMENT* 📢\n\n*{title}*\n{body}\n\n~ *System Broadcast*",
    sys_acc_app: "👋 *WELCOME TO LAMS!* 🎉\n\nHello *{name}*,\nYour faculty account has been *successfully verified and approved* by the Administration! ✅\n\nYou can now log in to manage your timetable, track attendance, and process substitutions seamlessly.\n\n🌐 _https://lams.vercel.app_",
    obs_sub_app: "🚨 *ADMIN ALERT: LEAVE COVERED* 🚨\n\nA substitution arrangement has been finalized.\n\n━━━━━━━━━━━━━━\n📋 *COVERAGE DETAILS*\n🔹 *On Leave:* {requesterName}\n🔹 *Substitute:* {subName}\n🔹 *Class:* {subject} ({group}){cofacInline}\n🔹 *When:* {day}, {date} at {time}\n🔹 *Room:* {room}\n━━━━━━━━━━━━━━",
    obs_sub_can: "⚠️ *ADMIN ALERT: SUB CANCELLED* ⚠️\n\nA substitution arrangement has been revoked.\n\n━━━━━━━━━━━━━━\n📋 *CANCELLATION DETAILS*\n🔹 *Class:* {subject} ({group}){cofacInline}\n🔹 *When:* {day}, {date} at {time}\n🔹 *Room:* {room}\n━━━━━━━━━━━━━━",
    obs_bday: "📢 *Admin Alert: Birthday Today!* 🎈\n\nToday is *{name}'s* birthday! Be sure to wish them! 🎂",
    obs_anni: "📢 *Admin Alert: Work Anniversary!* 🎊\n\n*{name}* is celebrating *{years} years* with us today! 🏫"
};
