export const defaultTemplates = {
    birthday_wa: "🎂 *HAPPY BIRTHDAY, {name}!* 🎂\n\nWishing you a fantastic day filled with joy, and a year ahead full of success and happiness! Keep inspiring! ✨🥂\n\n~ *LAMS Admin*",
    anniversary_wa: "🎊 *HAPPY WORK ANNIVERSARY!* 🎊\n\nCongratulations, *{name}*, on completing *{years}* with our institution! 🏫\n\nThank you for your incredible dedication and hard work. We are so proud to have you on our team! 🌟\n\n~ *College Management*",
    holiday_push_title: "🎉 Holiday Alert",
    holiday_push_body: "Today is {holiday_name}. No classes today. Enjoy!",
    holiday_wa: "🏝️ *HAPPY HOLIDAY!* 🏝️\n\nWishing everyone a wonderful *{holiday_name}*! 🎉\nHave a great time!\n\n~ *LAMS Admin*",
    warn1_push_title: "Upcoming Class",
    warn1_push_body: "🔔 Heads Up: {subject} ({group}){cofacInline} starts in {mins} mins at Room {room}.",
    warn1_wa: "🔔 *UPCOMING CLASS* 🔔\n\n📌 *{subject}* ({group})\n⏰ _Starts in:_ *{mins} mins*\n🏫 _Room:_ *{room}*{cofacStr}",
    warn2_push_title: "Class Starting!",
    warn2_push_body: "🚀 ACTION: Run to Room {room}! {subject} ({group}){cofacInline} is starting NOW!",
    warn2_wa: "🚀 *CLASS STARTING NOW!* 🚀\n\n🚨 _ACTION REQUIRED:_ Run to *Room {room}!*\n\n📌 *{subject}* ({group}) is starting *NOW!*{cofacStr}",
    weekly_header: "🗓️ *WEEKLY PREVIEW: {name}* 🗓️\n\n🎯 _Prep for the upcoming week!_\nYou have *{total_sessions} sessions* scheduled.\n\n",
    weekly_class_line: "🔹 *[{idx}]* ⏰ _{time}_\n 📌 *{subject}* ({group}){roomStr}{semStr}{cofacStr}{subStr}\n",
    weekly_footer: "\n🌐 _Check the portal for full timetable._\nGood luck for the week! 💪",
    morning_header: "✨ *GOOD MORNING, {name}!* ✨\n🗓️ _{day}_ | 📚 *{total_classes} Classes Today*\n\n",
    morning_class_line: "🔹 *[{idx}]* ⏰ _{time}_\n 📌 *{subject}* ({group}){roomStr}{semStr}{cofacStr}{subStr}\n",
    morning_footer: "\n💡 _Have a highly productive day!_\n~ *LAMS Admin*",
    sys_sub_req: "🔄 *NEW SUBSTITUTION REQUEST* 🔄\n\nHello *{name}*,\nYou have received a new substitution request from *{requesterName}*!\n\n📝 *Details*:\nClass: {subject} ({group})\nRoom: {room}\nWhen: *{day}*, {date} at {time}{cofacStr}\n\n👉 _Please log in to the portal to Accept or Reject._",
    sys_sub_app: "✅ *SUBSTITUTION APPROVED!* ✅\n\nGreat news, *{name}*!\nYour substitution request for *{subject}*{cofacInline} on *{day}*, {date} has been *officially approved*.\n\n📅 *Covered By*: {subName}\n\n~ *LAMS Admin*",
    sys_sub_rej: "❌ *SUBSTITUTION DECLINED* ❌\n\nHello *{name}*,\nUnfortunately, your substitution request for *{subject}*{cofacInline} on *{day}*, {date} has been *declined* or cancelled.\n\nℹ️ *Info*: Please log in to check the status.",
    sys_sub_acc: "🎉 *SUBSTITUTION ACCEPTED!* 🎉\n\nHello *{name}*,\nYour request for *{subject}*{cofacInline} on *{day}*, {date} has been *accepted* by *{subName}*!\n\n~ *LAMS Admin*",
    sys_sub_can: "⚠️ *SUBSTITUTION CANCELLED* ⚠️\n\nHello *{name}*,\nA previously requested substitution for *{subject}*{cofacInline} on *{day}*, {date} has been *cancelled*.\n\nℹ️ *Info*: You are expected to take this class.",
    sys_new_assign: "📚 *NEW CLASS ASSIGNMENT* 📚\n\nHello *{name}*,\n{body}\n\n~ *LAMS Admin*",
    sys_acc_app: "👋 *WELCOME TO LAMS, {name}!* 🎉\n\nYour account has been *successfully approved* by the Administrator! ✅\n\nYou can now log in and manage your classes, labs, and substitutions seamlessly.\n\n🌐 _https://lams.vercel.app_",
    obs_sub_app: "🚨 *Admin Alert: Leave Covered* 🚨\n\n*{requesterName}* is on leave on *{day}, {date}*.\n*{subName}* will cover the *{subject}*{cofacInline} class for ({group}) at *{time}* in Room *{room}*.",
    obs_sub_can: "⚠️ *Admin Alert: Sub Cancelled* ⚠️\n\nThe substitution arrangement for *{subject}*{cofacInline} on *{day}, {date}* at *{time}* in Room *{room}* has been cancelled.",
    obs_bday: "📢 *Admin Alert: Birthday Today!* 🎈\n\nToday is *{name}'s* birthday! Be sure to wish them! 🎂",
    obs_anni: "📢 *Admin Alert: Work Anniversary!* 🎊\n\n*{name}* is celebrating *{years} years* with us today! 🏫"
};
