import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import QRCode from 'qrcode';
import { storage } from '../lib/firebase';
import { ref, uploadBytes } from 'firebase/storage';
import { sortSemesters } from './sortUtils';

// Fixed Public URL: Points to the Public View Page
const getPublicScheduleUrl = () => {
    if (typeof window !== 'undefined') return window.location.origin + '/#/view';
    return 'https://lams-final-version.vercel.app/#/view';
};


 
export const generateTimetablePDF = async (data, meta, shouldUpload = false) => {
    try {
        const doc = new jsPDF('landscape', 'mm', 'a4');
        const pageWidth = doc.internal.pageSize.width; // 297mm
        const pageHeight = doc.internal.pageSize.height; // 210mm
        const user = meta.user || 'Guest';
        let filterText = meta.filterText || '';

        // QR Code points to the FIXED public file
        const publicUrl = getPublicScheduleUrl();
        const qrUrl = await QRCode.toDataURL(publicUrl);

        // Truncate filter text if insanely long (prevent header blowout)
        if (filterText.length > 120) filterText = filterText.substring(0, 117) + '...';

        // --- 1. HEADER (Compact to maximize Schedule Space) ---
        // Header Background
        doc.setFillColor(255, 255, 255); // White
        doc.rect(0, 0, pageWidth, 18, 'F');

        // Brand Accent Line (Royal Blue)
        doc.setFillColor(37, 99, 235);
        doc.rect(0, 17.5, pageWidth, 0.5, 'F');

        // Title (Top Left)
        doc.setFont("helvetica", "bold");
        doc.setFontSize(18);
        doc.setTextColor(30, 41, 59);
        doc.text(meta.title?.toUpperCase() || "SCHEDULE", 10, 12);

        // QR Code (Top Right)
        // 16x16mm fits in 18mm header if placed at y=1 (Ends at 17mm, Line is at 17.5mm)
        // No overlap, Maximum Table Space.
        doc.addImage(qrUrl, 'PNG', pageWidth - 20, 1, 16, 16);

        // Metadata (Right Side - Shifted Left of QR)
        doc.setFont("helvetica", "normal");
        doc.setFontSize(7);
        doc.setTextColor(50, 50, 50);

        // Line 1: Generated info
        const timestamp = new Date().toLocaleDateString('en-GB');
        doc.text(`Generated by: ${user} | ${timestamp}`, pageWidth - 26, 7, { align: 'right' });

        // Line 2: Filter info
        doc.text(filterText, pageWidth - 26, 13, { align: 'right' });

        // --- 2. LAYOUT CALCULATION (Strict Single Page) ---
        // Reverted to 21mm to give maximum space to the schedule grid
        const startY = 21;
        const tableHeaderHeight = 8; // Height of the THEAD row
        const bottomMargin = 5; // Safe zone at bottom

        // CRITICAL: The actual space for CONTENT rows is Page - Start - Header - Margin
        const availableBodyHeight = pageHeight - startY - tableHeaderHeight - bottomMargin;

        const { days, timeSlots, assignments } = data;

        // Normalize helper (replicated from Scheduler to ensure matching)
         
        const normalizeTime = (t) => t ? t.toString().toLowerCase().replace(/\s+/g, '').replace(/[ap]m/g, '').replace(/\b0(\d):/g, '$1:') : '';

        // Density Calc
        const dayDensity = days.map(day => {
            let maxOverlap = 0;
            timeSlots.forEach(time => {
                const count = assignments.filter(a => a.day === day && normalizeTime(a.time) === normalizeTime(time)).length;
                if (count > maxOverlap) maxOverlap = count;
            });
            // Ensure at least 1 unit
            return Math.max(1, maxOverlap);
        });

        const totalUnits = dayDensity.reduce((sum, d) => sum + d, 0);

        // Dynamic Unit Height
        let unitHeight = availableBodyHeight / totalUnits;

        // Cap max height for aesthetics (if schedule is empty)
        if (unitHeight > 15) unitHeight = 15;

        // Font Size Calc
        let fontSize = Math.floor(unitHeight * 2);
        if (fontSize > 9) fontSize = 9;
        if (fontSize < 3.5) fontSize = 3.5; // Allow shrinking to 3.5pt for high density

        const rowHeights = dayDensity.map(d => d * unitHeight);

        const columns = [
            { header: '', dataKey: 'day' }, // Empty header for custom diagonal drawing
            ...timeSlots.map(t => ({ header: t.toUpperCase(), dataKey: t }))
        ];

        const rows = days.map((day, i) => {
            const row = { day };
            row.minHeight = rowHeights[i];
            row.density = dayDensity[i]; // Store density for grid drawing
            row.customData = {};

            timeSlots.forEach(time => {
                row[time] = "";
                const items = assignments
                    .filter(a => a.day === day && normalizeTime(a.time) === normalizeTime(time))
                    .sort(sortSemesters);
                row.customData[time] = items;
            });
            return row;
        });

        // --- 3. RENDER ---
        autoTable(doc, {
            startY: startY,
            columns: columns,
            body: rows,

            theme: 'grid',
            margin: { left: 5, right: 5, bottom: 2 },
            pageBreak: 'avoid',

            styles: {
                lineWidth: 0.4, // Uniform Bold Thickness
                lineColor: [0, 0, 0], // Pure Black
                textColor: [0, 0, 0],
                fontSize: fontSize,
                valign: 'middle',
                cellPadding: 0.5,
                overflow: 'hidden',
                minCellHeight: 0
            },
            headStyles: {
                fillColor: [239, 246, 255], // Premium Light Blue (Back to light for Black text)
                textColor: [0, 0, 0], // Pure Black Text as requested
                fontStyle: 'bold',
                halign: 'center',
                valign: 'middle',
                fontSize: 9,
                minCellHeight: tableHeaderHeight,
                lineWidth: 0.3,
                lineColor: [100, 100, 100]
            },
            columnStyles: {
                day: {
                    cellWidth: 15,
                    halign: 'center',
                    valign: 'middle',
                    fontStyle: 'bold',
                    fillColor: [248, 250, 252], // Slate 50 (Very subtle contrast)
                    lineWidth: 0.3,
                    textColor: [15, 23, 42], // Slate 900
                    lineColor: [226, 232, 240] // Slate 200
                }
            },

            didParseCell: function (data) {
                if (data.row.raw.minHeight) {
                    data.row.height = data.row.raw.minHeight;
                }
                if (data.section === 'body' && data.column.dataKey === 'day') {
                    data.cell.text = [];
                }
            },

            // eslint-disable-next-line sonarjs/cognitive-complexity
            didDrawCell: function (data) {
                // --- CUSTOM DAY RENDERER ---
                if (data.section === 'body' && data.column.dataKey === 'day') {
                    const text = data.row.raw.day || '';
                    const dayShort = String(text).substring(0, 3).toUpperCase();

                    const x = data.cell.x + data.cell.width / 2;
                    const y = data.cell.y + data.cell.height / 2;

                    doc.setFontSize(12); // Significantly Larger
                    doc.setFont("helvetica", "bold");
                    doc.setTextColor(0, 0, 0); // Pure Black
                    doc.setLineWidth(0.5); // Thicker text stroke simulation not needed for helvetica bold, but good to ensure reset
                    doc.text(dayShort, x, y, { align: 'center', baseline: 'middle' });
                }

                // --- HEADER LABEL FIX (Day/Time) ---
                if (data.section === 'head' && data.column.index === 0) {
                    const { x, y, width, height } = data.cell;

                    // Draw Diagonal Line
                    doc.setDrawColor(150, 150, 150);
                    doc.setLineWidth(0.2);
                    doc.line(x, y, x + width, y + height);

                    // Labels
                    doc.setFontSize(7);
                    doc.setTextColor(0, 0, 0);
                    doc.setFont("helvetica", "bold");

                    // 'TIME' (Top-Right)
                    doc.text('TIME', x + width - 2, y + 4, { align: 'right' });

                    // 'DAY' (Bottom-Left)
                    doc.text('DAY', x + 2, y + height - 2, { align: 'left' });
                }

                // --- SCHEDULE ITEMS & FULL GRID ---
                if (data.section === 'body' && data.column.dataKey !== 'day') {
                    // Draw FULL GRID lines - THIN internal lines
                    const density = data.row.raw.density || 1;
                    doc.setDrawColor(200, 200, 200); // Light Grey
                    doc.setLineWidth(0.1); // Thin internal lines

                    for (let i = 1; i < density; i++) {
                        const lineY = data.cell.y + (i * unitHeight);
                        doc.line(data.cell.x, lineY, data.cell.x + data.cell.width, lineY);
                    }

                    // Render Data Items
                    if (data.row.raw.customData) {
                        const items = data.row.raw.customData[data.column.dataKey];
                        if (Array.isArray(items) && items.length > 0) {
                            renderCompactCell(doc, items, data.cell.x, data.cell.y, data.cell.width, data.cell.height, unitHeight, fontSize);
                        }
                    }
                }

                // --- ROW SEPARATOR (User Request: Clear Day Distinction) ---
                if (data.section === 'body') {
                    // Draw a BOLD BLACK line at the bottom of the entire row (Day block)
                    doc.setDrawColor(0, 0, 0); // Pure Black
                    doc.setLineWidth(0.5); // Thick Outer Border
                    doc.line(data.cell.x, data.cell.y + data.cell.height, data.cell.x + data.cell.width, data.cell.y + data.cell.height);

                    // Also draw line at top if it's the very first row
                    if (data.row.index === 0) {
                        doc.line(data.cell.x, data.cell.y, data.cell.x + data.cell.width, data.cell.y);
                    }
                }

                // --- BOLD PERIMETER FIX (User Request) ---
                doc.setDrawColor(0, 0, 0);
                doc.setLineWidth(0.6); // Bold Frame

                // 1. Top Border (Header Top Edge)
                if (data.section === 'head') {
                    doc.line(data.cell.x, data.cell.y, data.cell.x + data.cell.width, data.cell.y);
                }

                // 2. Left Border (Table Left Edge)
                if (data.column.index === 0) {
                    doc.line(data.cell.x, data.cell.y, data.cell.x, data.cell.y + data.cell.height);

                    // EXTRA: Bold Vertical Separator (Day Column | Data Columns)
                    doc.line(data.cell.x + data.cell.width, data.cell.y, data.cell.x + data.cell.width, data.cell.y + data.cell.height);
                }

                // 3. Right Border (Table Right Edge)
                if (data.column.index === columns.length - 1) {
                    doc.line(data.cell.x + data.cell.width, data.cell.y, data.cell.x + data.cell.width, data.cell.y + data.cell.height);
                }
            }
        });

        // NO FOOTER AT ALL

        // --- FILENAME GENERATION ---
        const d = new Date();
        const dd = String(d.getDate()).padStart(2, '0');
        const mm = String(d.getMonth() + 1).padStart(2, '0');
        const yyyy = d.getFullYear();
        const dateStr = `${dd}${mm}${yyyy}`;

        // Get Academic Year from meta (fallback to title if missing, or generic)
        const rawYear = meta.academicYear || meta.title || "AcademicYear";
        // Sanitize: Allow letters, numbers, spaces, parens, hyphens. Remove illegal chars.
         
        const safeYear = rawYear.replace(/[^a-zA-Z0-9() -]/g, "").trim();

        const filename = `Schedule-${safeYear}-${dateStr}.pdf`;
        doc.save(filename);

        // --- UPLOAD LOGIC ---
        if (shouldUpload) {
            try {
                const pdfBlob = doc.output('blob');
                const storageRef = ref(storage, 'schedule_public.pdf');

                // Metadata for public access configuration
                const metadata = {
                    contentType: 'application/pdf',
                    cacheControl: 'public,max-age=300' // Cache for 5 mins
                };

                await uploadBytes(storageRef, pdfBlob, metadata);
                console.log("SUCCESS: Schedule published to Cloud Storage.");
                return getPublicScheduleUrl();

            } catch (uploadErr) {
                console.error("UPLOAD FAILED:", uploadErr);
                alert("Failed to publish schedule to cloud. Check console.");
            }
        }

    } catch (e) {
        console.error("PDF Fail:", e);
        throw e;
    }
};

// --- LINEAR COMPACT FORMATTER ---
function renderCompactCell(doc, items, x, y, w, h, unitHeight, baseFontSize) {
    // Vertical Safety: Ensure font fits in height
    // e.g. If unitHeight is 3mm, baseFontSize shouldn't be 10pt (3.5mm)
    let safeMaxFont = Math.floor((unitHeight - 0.5) * 2.83); // mm to pt approx
    if (safeMaxFont < 3) safeMaxFont = 3; // Allow 3pt minimum

    let fontSize = Math.min(baseFontSize, safeMaxFont);

    let currentY = y + (unitHeight * 0.65); // Centered baseline



    items.forEach((item, index) => {
        // Safe Data Extraction
        // Safe Data Extraction
        // Force display of all parts as per user request (regardless of view context)
        const deptStr = item.dept ? `${item.dept}-` : '';
        const section = item.section || '';
        const group = (item.group && item.group !== 'All') ? `-${item.group}` : '';
        const subjectName = item.subject || '';

        // Room: Always show
        const room = item.room || '';
        const roomStr = room ? `-${room}` : '';

        // Lab Detection
        const isLab = (item.type === 'lab') || (item.isLab === true) || (subjectName.toLowerCase().includes('lab') || (item.room || '').toLowerCase().includes('lab'));
         
        if (isLab) {
            // Future placeholder for lab-specific styling if needed
        }

        // Sem: Use passed short code + Ordinal + " SEM"
        let semStr = '';
        if (item.sem) {
            let sVal = item.sem.toString();

            // Helper: Add ordinal suffix if it's a raw number (e.g. "4" -> "4th")
             
            const addOrdinal = (n) => {
                const s = ["th", "st", "nd", "rd"];
                const v = n % 100;
                return n + (s[(v - 20) % 10] || s[v] || s[0]);
            };

            // If strict number, format it. If "4th" or "IV", leave it.
            if (!isNaN(sVal)) {
                sVal = addOrdinal(parseInt(sVal, 10));
            }

            // User Request: "4th SEM"
            semStr = `-${sVal} SEM`;
        }

        // Faculty: Always show short codes
        let facultyStr = '';
        const fac1 = item.faculty || '?';
        const fac2 = item.faculty2 ? `,${item.faculty2}` : '';
        facultyStr = fac1 ? `-${fac1}${fac2}` : '';

        // Construct Parts
        const part1 = `${deptStr}${section}${group}-`;
        const suffix = `${facultyStr}${roomStr}${semStr}`;
        const part2 = `${subjectName}`;
        const part3 = suffix;

        // Adjust visibility
        // If subject is missing, part2 is empty.

        // --- SMART HORIZONTAL FIT ---
        // Calc widths: Everything is BOLD now.
        doc.setFontSize(fontSize);

        // Parts 1 & 3: Bold
        doc.setFont("helvetica", "bold");
        const w1 = doc.getTextWidth(part1);
        const w3 = doc.getTextWidth(part3);

        // Part 2 (Subject): Larger Size (+0.5pt) & Bold
        doc.setFontSize(fontSize + 0.5);
        const w2 = doc.getTextWidth(part2);

        const totalW = w1 + w2 + w3;

        const safeZone = w - 1;
        let drawFontSize = fontSize;

        if (totalW > safeZone) {
            const ratio = safeZone / totalW;
            drawFontSize = Math.floor(fontSize * ratio * 10) / 10;
            if (drawFontSize < 3) drawFontSize = 3;
        }

        // --- DRAW ---
        doc.setFontSize(drawFontSize);
        doc.setTextColor(0, 0, 0);

        // 1. Prefix (Bold as per "all this i want bold")
        doc.setFont("helvetica", "bold");
        const finalW1 = doc.getTextWidth(part1);
        doc.text(part1, x + 0.5, currentY);

        // 2. Subject (Size + 0.5 & Extra Bold)
        // Increase size by 0.5 relative to the drawn size
        const subDrawSize = drawFontSize + 0.5;
        doc.setFontSize(subDrawSize);

        // Dynamic Line Width: 2.5% of font size for robust boldness
        const strokeWidth = subDrawSize * 0.3527 * 0.025;
        doc.setLineWidth(strokeWidth);
        doc.setDrawColor(0, 0, 0);
        doc.text(part2, x + 0.5 + finalW1, currentY, { renderingMode: 'fillThenStroke' });

        const finalW2 = doc.getTextWidth(part2);

        // Reset Font Size for Suffix
        doc.setFontSize(drawFontSize);

        // 3. Suffix (Bold)
        // Reset to normal fill mode
        // Add tiny buffer (strokeWidth) to avoid overlap with Subject's thick stroke
        doc.text(part3, x + 0.5 + finalW1 + finalW2 + (strokeWidth / 2), currentY, { renderingMode: 'fill' });

        // Separator
        if (index < items.length - 1) {
            doc.setDrawColor(100, 100, 100); // Darker line
            doc.setLineWidth(0.1);
            doc.line(x, y + ((index + 1) * unitHeight), x + w, y + ((index + 1) * unitHeight));
        }

        currentY += unitHeight;
    });
}
